PrestaDinero.WebDistribuidor/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using PrestaDinero.Core;
using PrestaDinero.Core.UnidadTrabajo;
using System.Linq;
using System.Threading.Tasks;

namespace PrestaDinero.WebDistribuidor.Controllers
{
    public class ClienteController : Controller
    {

        public readonly IUnidadTrabajo _unidadTrabajo;

        public ClienteController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public async Task<IActionResult> Index()
        {
            var (_, datos) = await _unidadTrabajo.Cliente.Listar();
            return View(datos.OrderBy(x=> x.Nombre).ThenBy(x=> x.ApellidoPaterno).ThenBy(x=> x.ApellidoMaterno).ToList());
        }

        public async Task<IActionResult> Create(int id)
        {
            var (response,datos) = await _unidadTrabajo.Cliente.Buscar(id);

            var cliente = datos;

            if (!response.Estado)
            {
                cliente = new ClienteEntity()
                {
                    Activo = true
                };
               
            }

            return View(cliente);
        }


        [HttpPost]
        public async Task<IActionResult> Create(ClienteEntity obj)
        {
         
           

            if (obj.IdCliente==0)
            {
                var (response, _) = await _unidadTrabajo.Cliente.Guardar(obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {

                var (response, _) = await _unidadTrabajo.Cliente.Modificar(obj.IdCliente,obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index");
                }
            }


            return View(obj);
        }
    }
}

PrestaDinero.WebDistribuidor/Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Mvc;
using PrestaDinero.Core;
using PrestaDinero.Core.UnidadTrabajo;
using System.Threading.Tasks;

namespace PrestaDinero.WebDistribuidor.Controllers
{
    public class DistribuidorController : Controller
    {

        public readonly IUnidadTrabajo _unidadTrabajo;

        public DistribuidorController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public async Task<IActionResult> Index()
        {
            var (_, datos) = await _unidadTrabajo.Distribuidor.Listar();
            return View(datos);
        }

        public async Task<IActionResult> Create(int id)
        {
            var (response, datos) = await _unidadTrabajo.Distribuidor.Buscar(id);
            var distribuidor = datos;
            if (!response.Estado)
            {
                 distribuidor = new DistribuidorEntity()
                {
                    Activo=true
                };
               
            }

            return View(distribuidor);
        }


        [HttpPost]
        public async Task<IActionResult> Create(DistribuidorEntity obj)
        {

            if (obj.IdDistribuidor == 0)
            {
                var (response, _) = await _unidadTrabajo.Distribuidor.Guardar(obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {

                var (response, _) = await _unidadTrabajo.Distribuidor.Modificar(obj.IdDistribuidor, obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(obj);
        }

        }
    }

PrestaDinero.WebDistribuidor/Controllers/ReportesController.cs
using Microsoft.AspNetCore.Mvc;
using PrestaDinero.Core.UnidadTrabajo;
using Rotativa.AspNetCore;
using System;
using System.Linq;

namespace PrestaDinero.WebDistribuidor.Controllers
{
    public class ReportesController : Controller
    {
        public readonly IUnidadTrabajo _unidadTrabajo;

        public ReportesController(IUnidadTrabajo unidadTrabajo)
        {

            _unidadTrabajo = unidadTrabajo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListaQuincenal()
        {
            ViewBag.Fecha = DateTime.Now;
            return PartialView();
        }

        [HttpPost]
        public IActionResult ListaQuincenal(DateTime fecha)
        {
            var datos = _unidadTrabajo.Reportes.ListaQuincenal(fecha);

            return new ViewAsPdf("RepListaQuincenal", datos.OrderBy(x=> x.Vale.Cliente.NombreCompleto).ToList(), viewData: ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins(10, 10, 20, 20),
              //  CustomSwitches = "--page-offset 0 --footer-left [page] --footer-font-size 8",
               PageOrientation=Rotativa.AspNetCore.Options.Orientation.Portrait,
            };
        }

        public IActionResult ImpresionVales()
        {

            return PartialView();
        }

        [HttpPost]
        public IActionResult ImpresionVales(DateTime fecha)
        {
            var datos = _unidadTrabajo.Reportes.ListaQuincenal(fecha);

            return new ViewAsPdf("RepImpresionVales", datos.OrderBy(x => x.Vale.Cliente.NombreCompleto).ToList(), viewData: ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins(10, 10, 20, 20),
                CustomSwitches = "--page-offset 0 --footer-left [page] --footer-font-size 8",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
            };
        }
   
        public IActionResult SaldoClientes()
        {
            return View();
        }
    
    
    }
}

PrestaDinero.WebDistribuidor/Controllers/TablaInteresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PrestaDinero.Core;
using PrestaDinero.Core.UnidadTrabajo;
using System.Linq;
using System.Threading.Tasks;

namespace PrestaDinero.WebDistribuidor.Controllers
{
    public class TablaInteresController : Controller
    {

 
        public readonly IUnidadTrabajo _unidadTrabajo;

        public TablaInteresController( IUnidadTrabajo unidadTrabajo)
        {
        
            _unidadTrabajo = unidadTrabajo;
        }

        public async Task<IActionResult> Index(int IdTipoPrestamo = 1)
        {

            var (_, datos) = await _unidadTrabajo.TablaInteres.Listar();
            datos= datos.Where(x => x.IdTipoPrestamo == IdTipoPrestamo).ToList();
         

            var (_, tipoPrestamo) = await _unidadTrabajo.TipoPrestamo.Listar();      
            ViewBag.TipoPrestamos = new SelectList(tipoPrestamo, "IdTipoPrestamo", "Nombre",IdTipoPrestamo);

            return View(datos);
        }


        public async Task<IActionResult> Create(int id)
        {
            var (response, datos) = await _unidadTrabajo.TablaInteres.Buscar(id);

            var tablaInteres = datos;
            if (!response.Estado)
            {
                tablaInteres = new TablaInteresEntity()
                {
                    Activo = true
                };
              
            }

            return View(tablaInteres);
        }


        [HttpPost]
        public async Task<IActionResult> Create(TablaInteresEntity obj)
        {
            if (obj.IdTablaInteres == 0)
            {
                var (response, _) = await _unidadTrabajo.TablaInteres.Guardar(obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index",new { obj.IdTipoPrestamo});
                }
            }
            else
            {

                var (response, _) = await _unidadTrabajo.TablaInteres.Modificar(obj.IdTablaInteres, obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index", new { obj.IdTipoPrestamo });
                }
            }
            return View(obj);
        }

    }
}

PrestaDinero.WebDistribuidor/Controllers/ValeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PrestaDinero.Core;
using PrestaDinero.Core.DTOS;
using PrestaDinero.Core.UnidadTrabajo;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PrestaDinero.WebDistribuidor.Controllers
{
    [Route("{Controller}/{action}")]
    public class ValeController : Controller
    {

        public readonly IUnidadTrabajo _unidadTrabajo;

        public ValeController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public async Task<IActionResult> Index()
        {
           var (_,datos) = await _unidadTrabajo.Vale.Listar();
            return View(datos.Where(x => x.EstaPagado == false).OrderBy(x=> x.Fecha).ToList());
        }



        public async Task<IActionResult> Create(int id =0)
        {
            var (_, vale) = await _unidadTrabajo.Vale.Buscar(id);

            if (vale==null)
            { 
                 vale = new ValeEntity  
                {
                    Dispocision = 1000,
                    Fecha = DateTime.Now,
                    FechaPrimerPago = DateTime.Now,
                    IdDistribuidor = 1,
                };
            }
            var (_,clientes) = await _unidadTrabajo.Cliente.Listar();
            var (_, tipoPrestamos) = await _unidadTrabajo.TipoPrestamo.Listar();

            ViewBag.Clientes = new SelectList(clientes.Where(x => x.Activo).OrderBy(x => x.NombreCompleto).ToList(), "IdCliente", "NombreCompleto");
            ViewBag.TipoPrestamos = new SelectList(tipoPrestamos.Where(x => x.Activo).ToList(), "IdTipoPrestamo", "Nombre");
            return View(vale);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ValeEntity vale)
        {


            await _unidadTrabajo.Vale.Guardar(vale);
            return RedirectToAction("index");
        }


        [HttpPost]
        public async Task<IActionResult> Calcular(ValeEntity obj)
        {

            var ( _, detalles) = await _unidadTrabajo.Vale.Calcular(obj);
            obj.ValeDetalle = detalles;

            var (_, clientes) = await _unidadTrabajo.Cliente.Listar();
            var (_, tipoPrestamos) = await _unidadTrabajo.TipoPrestamo.Listar();

            ViewBag.Clientes = new SelectList(clientes.Where(x => x.Activo).OrderBy(x => x.NombreCompleto).ToList(), "IdCliente", "NombreCompleto");
            ViewBag.TipoPrestamos = new SelectList(tipoPrestamos.Where(x => x.Activo).ToList(), "IdTipoPrestamo", "Nombre");
            return View("Create", obj);
        }






        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var v = await _unidadTrabajo.Vale.Buscar(id);

            var updateVale = new UpdateVale
            {
                IdVale = v.datos.IdVale,
                IdCliente = v.datos.IdCliente,
                FechaDisposicion = v.datos.Fecha
            };

            var (_, clientes) = await _unidadTrabajo.Cliente.Listar();

            ViewBag.Clientes = new SelectList(clientes.Where(x => x.Activo).OrderBy(x => x.NombreCompleto).ToList(), "IdCliente", "NombreCompleto");

            return View(updateVale);
        }


        [HttpPost]
        public async Task<IActionResult> Update(UpdateVale obj)
        {

            var vale = await _unidadTrabajo.Vale.Buscar(obj.IdVale);

            vale.datos.Fecha = obj.FechaDisposicion;
            vale.datos.IdCliente = obj.IdCliente;

            await _unidadTrabajo.Vale.Modificar(obj.IdVale, vale.datos);

            return RedirectToAction("Index");
        }



        [Route("{id}")]
        public async Task<ActionResult> Delete(int id)
        {
            var (_, vale) = await _unidadTrabajo.Vale.Buscar(id);
            return PartialView(vale);
        }

        [HttpPost]
        [Route("{id}")]
        public async Task<ActionResult> Delete(ValeEntity obj)
        {
            await _unidadTrabajo.Vale.Borrar(obj.IdVale);
            return RedirectToAction("Index");
        }






    }
}

PrestaDinero.WebDistribuidor/Views/Shared/_Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        @*Anything you want*@
    </div>
    <!-- Default to the left -->
    @*<strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.*@
</footer>
</div>

PrestaDinero.WebDistribuidor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Presta dinero</title>

    <partial name="_css" />

    @RenderSection("Styles", required: false)
</head>
<body class=" sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed" style="height: auto;">


    <partial name="_Navbar" />
    <partial name="_SideBar" />


    @RenderBody()

    <partial name="_Footer" />

    <partial name="_js" />

    @RenderSection("Scripts", required: false)

</body>
</html>

PrestaDinero.WebDistribuidor/Views/Shared/_Navbar.cshtml
<!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-dark">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
          
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">
                <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                    <i class="fas fa-search"></i>
                </a>
                <div class="navbar-search-block">
                    <form class="form-inline">
                        <div class="input-group input-group-sm">
                            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-navbar" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                  
                </a>

            
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    
                </a>
            
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                    <i class="fas fa-th-large"></i>
                </a>
            </li>
        </ul>
    </nav>
<!-- /.navbar -->

PrestaDinero.WebDistribuidor/Views/Shared/_Reporte.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>



    @RenderBody()


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PrestaDinero.WebDistribuidor/Views/Shared/_SideBar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a asp-controller="Home" asp-action="Index" class="brand-link">
        <img src="~/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Presto Dinero</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/adminlte/dist/img/avatar2.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">
                    Laura E. Santiesteban 
                </a>
                <a asp-controller="Home" asp-action="Logout" >LogOut</a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Distribuidor" class="nav-link">
                        <i class="nav-icon fas fa-user-tie"></i>
                        <p>
                            Distribuidores
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Cliente" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Clientes

                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Vale" class="nav-link">
                        <i class="nav-icon fas fa-id-card"></i>
                        <p>
                            Vales
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-action="Index" asp-controller="TipoPrestamo" class="nav-link">
                        <i class="nav-icon fas fa-id-card"></i>
                        <p>
                            Tipo de prestamo
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="TablaInteres" class="nav-link">
                        <i class="nav-icon fas fa-id-card"></i>
                        <p>
                            Tabla de interes
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Reportes" class="nav-link">
                        <i class="nav-icon fas fa-list-alt"></i>
                        <p>
                            Reportes
                        </p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>

PrestaDinero.WebDistribuidor/Views/Shared/_css.cshtml
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

PrestaDinero.WebDistribuidor/Views/Shared/_js.cshtml
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
<script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/adminlte/dist/js/adminlte.min.js"></script>