PrestaDinero.WebDistribuidor/Controllers/TipoPrestamoController.cs
using Microsoft.AspNetCore.Mvc;
using PrestaDinero.Core;
using PrestaDinero.Core.UnidadTrabajo;
using System.Threading.Tasks;

namespace PrestaDinero.WebDistribuidor.Controllers
{
    public class TipoPrestamoController : Controller
    {

        public readonly IUnidadTrabajo _unidadTrabajo;

        public TipoPrestamoController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public async Task<IActionResult> Index()
        {
            var (_, datos) = await _unidadTrabajo.TipoPrestamo.Listar();
            return View(datos);
        }

        public async Task<IActionResult> Create(int id)
        {
            var (response, datos) = await _unidadTrabajo.TipoPrestamo.Buscar(id);
           

           var  tipoPrestamo = datos;
            if (response.Estado==false)
            {
               tipoPrestamo= new TipoPrestamoEntity
                {
                    Activo = true
                };   
            }

            return View(tipoPrestamo);
        }


        [HttpPost]
        public async Task<IActionResult> Create(TipoPrestamoEntity obj)
        {           
            if (obj.IdTipoPrestamo == 0)
            {
                var (response, _) = await _unidadTrabajo.TipoPrestamo.Guardar(obj);

                if (response.Estado)
                {
                    await _unidadTrabajo.TablaInteres.Calcular(obj.IdTipoPrestamo);
                    return RedirectToAction("Index");
                }
            }
            else
            {

                var (response, _) = await _unidadTrabajo.TipoPrestamo.Modificar(obj.IdTipoPrestamo, obj);

                if (response.Estado)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(obj);
        }

    }
}

PrestaDinero.WebDistribuidor/Views/TipoPrestamo/Create.cshtml
@model PrestaDinero.Core.TipoPrestamoEntity

<div class="content-wrapper">

    <section class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">

                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>


    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Tipo de prestamos</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">

                            <form asp-action="Create" asp-controller="TipoPrestamo" method="post">

                                <input type="hidden" asp-for="IdTipoPrestamo">


                                <div class="card-body">
                                    <div class="form-group">
                                        <label asp-for="Nombre" class="label-control"></label>
                                        <input asp-for="Nombre" class="form-control">
                                        <span asp-validation-for="Nombre" class="text-danger"></span>
                                    </div>
                                   

                               
                            
                                    <div class="form-group">
                                        <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                            <input type="checkbox" class="custom-control-input" asp-for="Activo">
                                            <label class="custom-control-label" asp-for="Activo">
                                                Estatus
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer text-right">

                                    <a asp-controller="TipoPrestamo" asp-action="Index" class="btn btn-secondary">
                                        Regresar
                                    </a>
                                    <input type="submit" value="Guardar" class="btn btn-success swalDefaultSuccess">
                                </div>
                            </form>
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
    </section>

</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/adminlte/plugins/inputmask/jquery.inputmask.min.js"></script>
    <script src="~/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>


    <script>
        $(document).ready(function () {
            $(":input").inputmask();
            or
            Inputmask().mask(document.querySelectorAll("input"));
        });


        $(function () {
            var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
            });

            $('.swalDefaultSuccess').click(function () {
                Toast.fire({
                    icon: 'success',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });



    </script>
}

PrestaDinero.WebDistribuidor/Views/TipoPrestamo/Index.cshtml
@model List<PrestaDinero.Core.TipoPrestamoEntity>

<div class="content-wrapper swalDefaultSuccess">

    <section class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">

                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>


    <section class="content">
        <div class="container">



            <div class="row">
                <div class="col-12">

                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Tipo prestamo</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">


                            <div class="col-12  mb-4 text-right">
                               
                                    <a type="button" class="btn  btn-success" asp-action="Create" asp-controller="TipoPrestamo"><i class="fa fa-plus"></i> <span class="ml-2">Nuevo</span> </a>
                                   
                          
                            </div>

                            <div class=" table-responsive p-0">
                                <table class="table table-hover text-nowrap">
                                    <thead>
                                        <tr>
                                            <th>@Html.DisplayNameFor(item => item.FirstOrDefault().Nombre)</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @if (Model != null)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(Items => item.Nombre)</td>
                                                    <td class="text-right  py-0 align-middle">
                                                        <div class="btn-group btn-group-sm ">
                                                            <a href="#" class="btn btn-info"><i class="fas fa-eye"></i></a>
                                                            <a asp-action="Create" asp-controller="TipoPrestamo" asp-route-id="@item.IdTipoPrestamo" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                                                          
                                                        </div>
                                                    </td>
                                                </tr>
                                            }

                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
    </section>

</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

   
    <script src="~/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>


    <script>
        
        $(function () {
            var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
            });

            $('.swalDefaultSuccess').click(function () {
                Toast.fire({
                    icon: 'success',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });


    </script>
}